### ISSUE TITLE
Request: offer testimonials about your experience with The Workbench

### ISSUE THREAD

**Issue by zkamvar** [carpentries/lesson-development-training#109]
Hello friends, as all of you have experience using The Workbench, I am keen to start collecting testimonials to get others excited about developing lessons with The Workbench. 

If you are interested, I've created a testimonial category in The Workbench discussion forum: https://github.com/carpentries/workbench/discussions/categories/testimonials and I would really like to hear your thoughts about what you see as going well in the workbench (I've already seen some, but it would be nice to broadcast these wider ^_^)

**Comment by tobyhodges** [comment]
https://github.com/carpentries/workbench/discussions/23

**Comment by tobyhodges** [comment]
A note to my collaborators here: your testimonials would understandably carry more weight than mine, as (even though I meant what I wrote) I could easily be considered biased as a paid member of The Carpentries Curriculum Team.

**Comment by sstevens2** [comment]
done!

**Comment by tobyhodges** [comment]
Closing this now, but please re-open if you would like more from us on this @zkamvar
