### ISSUE TITLE
Consider expanding exercise on project governance

### ISSUE THREAD

**Issue by tobyhodges** [carpentries/lesson-development-training#124]
See https://github.com/carpentries/lesson-development-training/pull/122#issuecomment-1195802315

I suspect a more practical formative assessment on Martha's Rules/project governance will provide more feedback to learners and trainers about learners' mental models for how to apply the Rules (or devise something similar) in their own projects.

**Comment by tobyhodges** [comment]
After the second alpha pilot, Trainers reflected that this exercise had elicited a very insightful discussion among the participants, encouraging them to engage with the utility and value of governance and the challenges associated with introducing and following it. Based on that experience, I am now not sure if we need to change much here. This would be a good topic of conversation for Trainer Training (cc @sstevens2, as this relates to https://github.com/carpentries/lessondev-trainer-training/issues/5)

**Comment by sstevens2** [comment]
Sorry I missed this and didn't include it in the collab episode of trainer training.  Maybe we could have it as a topic for trainer meeting in the future?
