### ISSUE TITLE
Update CodiMD pilot template for trainers with new exercises for project management and governance

### ISSUE THREAD

**Issue by anenadic** [carpentries/lesson-development-training#127]

**Comment by tobyhodges** [comment]
After discussion at the August 2023 Maintainers meeting, we are removing the "high priority" label from this, to acknowledge that a lot more changes are expected to the curriculum in the next few weeks and the CodiMD template will need to be more generally updated to reflect those. Our conclusion was to aim for two things:

1. to create an updated notes doc template for the training matching the version of the curriculum that forms [the beta release](https://github.com/carpentries/lesson-development-training/milestone/4). This issue can be closed when that is done.
2. to explore possibilities for automatic creation of the CodiMD template. #238 has been opened to track that.

**Comment by tobyhodges** [comment]
I have updated [the template notes CodiMD doc](https://codimd.carpentries.org/cldt-notes-template) to reflect the current state of the curriculum. I am closing this issue now.
