### ISSUE TITLE
Reorganise episodes 22 and 24 into 3 episodes

### ISSUE THREAD

**Issue by anenadic** [carpentries/lesson-development-training#128]
Extract sections on project management and project governance from episode 24 into a separate episode. Reverse order of  episodes 22 and 24.

_[update from @tobyhodges since numeric prefixes were removed from episode filenames: these are the two "Collaborating..." episodes.]_

**Comment by anenadic** [comment]
@mkuzak Can you provide the link to documentation we mentioned at the meeting on 2022-07-26.

**Comment by anenadic** [comment]
Related to #59.

**Comment by tobyhodges** [comment]
Closed by #258
