### ISSUE TITLE
Think of adding an exercise "Check notifications on your repo" in collaborating with your team episode

### ISSUE THREAD

**Issue by anenadic** [carpentries/lesson-development-training#129]
This exercise should ask people to “review the notification settings on their lesson repository to make sure they are correct and as they’d like them to be”. We might try this exercise at pilot https://github.com/carpentries-incubator/python-intermediate-development/issues/1 and see if it needs adding tot he material.

**Comment by tobyhodges** [comment]
I will be happy for this to be added, but we need to resolve #138 first

**Comment by anenadic** [comment]
From maintainers meeting on 2023-09-01, the consensus was to try and add an exercise and tell learners to initially turn all notifications on on their repository - in order to see what level of comms that means for them and also so that they do not miss out on any changes/events on their lesson repo, with an idea that they can later on go and decrease the level of notifications if that what they want.
