### ISSUE TITLE
Template defaults update

### ISSUE THREAD

**Issue by zkamvar** [carpentries/lesson-development-training#146]
Hi all, I just wanted to let you know that the default template has updated so that the episodes are no longer created with numeric prefixes by default (see discussion at https://github.com/carpentries/sandpaper/issues/330 and [the release notes for version 0.10.0](https://carpentries.github.io/sandpaper/news/index.html#sandpaper-0100)). 

The new pattern is that episodes are created and added to the `config.yaml`.

In this lesson, this is the main section that will be affected:

https://github.com/carpentries/lesson-development-training/blob/f5f052ebda96974ec0895daf503dc021a23e4fd5/episodes/07-infrastructure.md?plain=1#L299-L319

Unfortunately, this throws a bit of a wrench in these plans as this requires another commit to add the episode to the schedule.

**Comment by tobyhodges** [comment]
Closed by #151
