### ISSUE TITLE
Preparing Checkpoints

### ISSUE THREAD

**Issue by sstevens2** [carpentries/lesson-development-training#15]
Not sure where to add it in the _preparing_ to teach episode but would like to add we suggest preparing your checkpoints.  It is easy to get nervous or in the flow of the lesson and forget to check-in with learners, especially with a new lesson.  I used to write it into my notes.  I would look through the episodes and in places where there weren't many exercises I would plan to pause and ask learners to signal with stickies or zoom reactions.

This is especially important at the beginning of a lesson.  There aren't many exercises at the beginning typically and if a learner doesn't get the tool open or package installed, they often won't interject.  If I ask, I can make it clear early on that I want to make sure everyone can follow along.

**Comment by tobyhodges** [comment]
@sstevens2 would you like to add this in before the pilot next week? I think it will make most sense as an additional bullet point in the list at https://carpentries.github.io/lesson-development-training/instructor/18-preparing.html#teaching-plan

**Comment by tobyhodges** [comment]
Addressed by @sstevens2 in #145
