### ISSUE TITLE
Add link to SMART framework for goals

### ISSUE THREAD

**Issue by anenadic** [carpentries/lesson-development-training#169]
In episode objectives.md

**Comment by tobyhodges** [comment]
Making notes as I go along: https://en.wikipedia.org/wiki/SMART_criteria#Common_usage may be the best choice. 

The framework was originally developed for managers, to aid in definition of business goals - the reference for that original definition is easy to find (https://community.mis.temple.edu/mis0855002fall2015/files/2015/10/S.M.A.R.T-Way-Management-Review.pdf), but it has been more difficult to identify the first instance of the framework being applied in an educational context.
