### ISSUE TITLE
Explain readme.md briefly before exercise in 07-infrastructure

### ISSUE THREAD

**Issue by anenadic** [carpentries/lesson-development-training#172]
In episode 07-infrastructure, an exercise on `readme.md` is introduced before `readme.md` is explained, even briefly. 

The suggestion is to have a subsection named 'readme.md' just below section `config.yml` but before the exercise and move the intro text from the exercise above the exercise into this section:

"The README.md file is the “front page” of your lesson repository on GitHub, and is written in Markdown. You should use it to provide basic information about the project, for anyone who finds their way to the source files for your lesson."

**Comment by tobyhodges** [comment]
Sounds good to me, @anenadic. Please go ahead and make a PR when you are ready.
