### ISSUE TITLE
Add config.yml to list of example files in the repository root in 07-infrastructure

### ISSUE THREAD

**Issue by anenadic** [carpentries/lesson-development-training#173]
In 07-infrastructure, add config.yml to the list of files mentioned in the root of a lesson repository. Currently, that list contains:
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- LICENSE.md
- README.md
- .gitignore
- and the .github/ folder
but it makes sense to add config.yml too.

**Comment by anenadic** [comment]
It does make sense @tobyhodges and it is clearly explained in the episode text - just wondering if learners will get that distinction at this point (and I should also read the text more carefully 😊 ). They may see that file in their repos and wonder why it is not mentioned (we do mention it later on in that episode so that may be sufficient) - I am happy to close this issue as `won't fix`.

**Comment by tobyhodges** [comment]
How about a compromise: we add a note for Trainers at this point, advising them not to dwell too long on the list, because the other files and folders will be covered before the end of the episode?

**Comment by tobyhodges** [comment]
Sounds good to me - happy to leave it to you 👍

**Comment by tobyhodges** [comment]
Closed by #176
