### ISSUE TITLE
Suggestion to incorporate a quote from Greg Wilson in Operations

### ISSUE THREAD

**Issue by anenadic** [carpentries/lesson-development-training#180]
I like this quote by Greg Wilson:
> "No lesson survives first contact with learners"

from https://third-bit.com/talks/writing-book/#19 that could go nicely at: https://carpentries.github.io/lesson-development-training/operations.html#pilot-workshops.

**Comment by anenadic** [comment]
Are we in agreement to add this quote? This was a suggestion only so checking with the team @tobyhodges @sstevens2 @mkuzak.

**Comment by tobyhodges** [comment]
I'm happy to include it.

**Comment by sstevens2** [comment]
Me too.
