### ISSUE TITLE
Add examples of misconceptions

### ISSUE THREAD

**Issue by tobyhodges** [carpentries/lesson-development-training#181]
Feedback from a recent training included a suggestion to add a few examples of miconceptions that could be addressed by MCQs before setting trainees off with the "design an MCQ" exericse. The mental arithmetic exercise from Instructor Training is good, but probably too far removed from the typical content of a lesson in our community to be directly relevant.
We could aim for one technical misconception (i.e. some common misconception in novices to programming) and one less dependent on familiarity with any particular prgramming language, e.g. a misconception around copyright/licensing.

**Comment by anenadic** [comment]
This is related to #177 and PR #290. Both this and issue #177 talk about adding more examples of misconceptions and MCQs (which are two different things) but I should have seen this issue before I did PR #290. I shall now go back to the PR and try to address both.

**Comment by tobyhodges** [comment]
This was addressed by @anenadic in #290
