### ISSUE TITLE
address Rproj file in initial setup/config instructions

### ISSUE THREAD

**Issue by tobyhodges** [carpentries/lesson-development-training#182]
Trainees using the R Markdown-flavoured repository template get a `FIXME.Rproj` file in their repository. We should add a callout about what needs to be done to that file in the intial setup and configuration steps covered in the infrastructure episode. I _think_ this is as straightforward as renaming the file to something more descriptive of the project, but pinging @zkamvar to confirm.

**Comment by zkamvar** [comment]
Correct. Changing the file name will be sufficient.
