### ISSUE TITLE
Make use of "Use your GH Pages website" checkbox

### ISSUE THREAD

**Issue by tobyhodges** [carpentries/lesson-development-training#186]
In the Workbench episode, we can now use the checkbox to set the lesson site URL in the repoisitory _About_ box instead of copy/pasting the site URL from the settings page.

**Comment by sstevens2** [comment]
I'm planning to use this as an example tomorrow in an Instructor Training Meeting tomorrow to demo on how to make a PR in github.  Adding in the changes I'll make below so I don't have to recreate them during the demo but can copy them from here.

First Change...above callout
Now, copy the URL in the box: this will be the address of your lesson site. -> You may copy the URL in this box, this will be the address of your lesson site.

2nd change, below callout
Paste the Pages URL into the Website box and click Save changes. -> Check the box that says "Use your GitHub Pages website" to add the address of your lesson site to the About box.
