### ISSUE TITLE
Move protecting main branch section

### ISSUE THREAD

**Issue by sstevens2** [carpentries/lesson-development-training#193]
[Episode 24 - collaborating](https://carpentries.github.io/lesson-development-training/collaborating.html) - Move the protecting the main branch part until after we've submitted a PR.   Also optionally maybe a mention or callout instead of a demo?

**Comment by tobyhodges** [comment]
+1 to saving time by making this a callout or a mention-with-link-to-learn-more, rather than a demo.

**Comment by tobyhodges** [comment]
Closed by #258 via #259
