### ISSUE TITLE
Remind folks of CoC in part 2

### ISSUE THREAD

**Issue by sstevens2** [carpentries/lesson-development-training#198]
Suggestion from the 2nd pilot that we remind people of the CoC and hand raising when we return for part 2 (days 5&6)

**Comment by tobyhodges** [comment]
Adding a bit more detail here for anyone who might want to take this on: I believe the idea is to add an Instructor Note to the beginning of _Reflecting on Trial Runs_ (`episodes/reflecting.md`) that reminds Trainers to mention the code of conduct and run through the "house rules" about keeping microphones muted, raising hands, etc at the beginning of part 2 of the training.
