### ISSUE TITLE
Narrative & example dataset before exercise design?

### ISSUE THREAD

**Issue by tobyhodges** [carpentries/lesson-development-training#210]
I have been wondering if the discussion of lesson narrative and example datasets should be moved to appear before trainees begin designing exercises to assess progress towards objectives. The part of [the narrative episode](https://carpentries.github.io/lesson-development-training/narrative.html) about finding example images could quite easily be moved to _How to Write a Lesson_, arguably a more appropriate place for that content anyway.

Pro:

- it could make it easier for trainees to design assessments, based on a narrative and/or some real data they have already found/discussed with their collaborators
- it reduces the likelihood that trainees will need to re-write the exercises they design to fit an example dataset/narrative they have found

Con:

- We haven't had much feedback so far that indicated participants would have liked this section to appear sooner in the training
- It would require an adjustment to the training schedule, break times, etc.

**Comment by AnnBackhaus** [comment]
When I think about my learning/training experiences, most are without stories, ie, I've learnt process or facts or 'content', followed (ideally) by application. If I use this as my baseline during my own lesson development (ie, content sans storyline), I am focused on learning objectives and making sure all content, activities, and assessments are relevant and supporting the objectives. I view adding a story later, on top, as an iterative development step. This provides me a second opportunity to look afresh at my materials, and ask myself "Does everything align to learning objectives?" Yes (keep), or No (throw). Then, how will this story further make cohesive (and "enliven" / make real) this learning experience? (In short, keep where it is)

**Comment by tobyhodges** [comment]
It looks like there is no strong desire to make this change, and we have plenty of other things to focus our efforts on, so I am closing this.
