### ISSUE TITLE
add info about alt text when discussing images

### ISSUE THREAD

**Issue by ErinBecker** [carpentries/lesson-development-training#226]
In https://carpentries.github.io/lesson-development-training/15-narrative.html let's add some information about why alt text is important.

**Comment by tobyhodges** [comment]
We cover alternative text later, in https://carpentries.github.io/lesson-development-training/explanation.html#other-important-considerations-for-lesson-text, which includes a short exercise on the topic. Do you think this should come earlier in the curriculum?

**Comment by ErinBecker** [comment]
Nope! I just didn't remember seeing it in the other episode. I'll close this issue as resolved.
