### ISSUE TITLE
Revisit/update section on milestones/project boards in episode on collaboration

### ISSUE THREAD

**Issue by anenadic** [carpentries/lesson-development-training#229]
Sentence 'Both Project Boards and Milestones are a way of organising issues into smaller “sub-projects” (i.e. smaller than the “project” represented by the whole repository).' is potentially misleading as projects in GitHub now can span multiple projects/repos. The whole section on milestones and project boards probably needs updating.

**Comment by tobyhodges** [comment]
Related to #197 and #138
