### ISSUE TITLE
Callout on different stages of a CITATION file

### ISSUE THREAD

**Issue by tobyhodges** [carpentries/lesson-development-training#23]
In `newcomers`, we might want to mention DOIs and what you might put as citation info before a lesson has an full journal citation.

**Comment by anenadic** [comment]
I've added a mention of DOIs and that we recommend to get one the moment the lesson reached the beta stage (is this correct?). Expanding on this in a callout is a great idea.

**Comment by anenadic** [comment]
I've improved the text around this in 7798a2d.
