### ISSUE TITLE
Condense collaboration recommendations

### ISSUE THREAD

**Issue by tobyhodges** [carpentries/lesson-development-training#233]
@jt14den expressed a desire for some of the collaboration material to be condensed down, and I wondered about a "Top Ten Tips"-style list akin to [the list of recommendations for teaching by participatory live demo](https://carpentries.github.io/instructor-training/17-live.html#top-ten-tips-for-participatory-live-coding-in-a-workshop) in the Instructor Training curriculum.

Would anyone else support this idea? Want to get us started on what our top ten tips might be?

**Comment by anenadic** [comment]
Here are some ideas from the top of my head and closely following our existing curriculum - to kick start the discussion:
- Identify target audience for your lesson
- Define desired learning outcomes for the lesson
- Define an (ideally authentic) example dataset or narrative for the lesson 
- Design assessments to determine progress towards desired outcomes and to fit the example dataset/narrative chosen
- Write content to lead learners from one of the assessments to the next following the story you are telling with your lesson
- Assess learner progress towards outcomes during teaching
- Pilot your lesson and evaluate how closely the outcomes meet the objectives. 
- Refine the lesson based on the feedback from pilots.
- Keep to scope of your target audience and lesson objectives. It is OK to say 'No'.
- Do not do it alone - collaborate with your team

**Comment by tobyhodges** [comment]
>     * Identify target audience for your lesson
> 
>     * Define desired learning outcomes for the lesson
> 
>     * Define an (ideally authentic) example dataset or narrative for the lesson
> 
>     * Design assessments to determine progress towards desired outcomes and to fit the example dataset/narrative chosen
> 
>     * Write content to lead learners from one of the assessments to the next following the story you are telling with your lesson
> 
>     * Assess learner progress towards outcomes during teaching
> 
>     * Pilot your lesson and evaluate how closely the outcomes meet the objectives.
> 
>     * Refine the lesson based on the feedback from pilots.
> 
>     * Keep to scope of your target audience and lesson objectives. It is OK to say 'No'.
> 
>     * Do not do it alone - collaborate with your team

Thanks @anenadic: I was looking for ten tips for (open source) collaboration, specifically, but this is a great summary of the key points of the curriculum as a whole. I think we could add this to the final wrap-up. In fact, maybe we could add developing a list like this as another suggested activity for [the reflection exercise](https://carpentries.github.io/lesson-development-training/27-wrap-up3.html#reflection-exercise-15-min) in that last episode? Then we could include your list in a solution block for that exercise, framed as a suggestion rather than a "correct" answer?

**Comment by anenadic** [comment]
Ha! I misunderstood (did not read the issue title properly) and was also going to suggest we do this as an exercise with our current trainer training cohort to get everyone's opinions. So I agree we could add this as the reflection exercise in the last episode - will open a separate issue for that. Back to the drawing board for this issue :-).

**Comment by anenadic** [comment]
I like that [CodiMD mentioned above](https://github.com/carpentries/lesson-development-training/issues/233#issuecomment-1689689554) - especially the point on different expertise and skills they bring to a collaborative project. Here is mix of some general and lesson development specific points on collaboration (the latter I tried to extract from our curriculum):

1. Record and manage issues with your lesson as you develop, trial and maintain it (e.g. assign people responsible for issues, categorise and prioritise them, etc.)
2. Provide ‘external-facing’ features for your lesson (such as documentation, contribution and how to get involved guides, preferred way of communication, etc.)
3. Manage contributions in a timely manner (e.g. noticing when things happen, responding to PRs, etc.)
4. Be open and welcoming to new contributors, provide different options for contributing or point to upskilling guides (or run upskilling sessions if possible) to bring people up to speed 
5. Value everyone's contributions to the project and make sure you show your appreciation (or something about different expertise and skills they bring to a collaborative project and how it is nice when they complement each other from that [CodiMD](https://github.com/carpentries/lesson-development-training/issues/233#issuecomment-1689689554))
6. Plan your meetings to get the most out of your team and be appreciative of people's times (set agenda, assign meeting roles (chair, notetaker, time-keeper), etc.) 
7. Assign responsibilities for tasks and actions (to stay on target)
8. Share information and communicate synchronously and asynchronously 
9. Document and share knowledge to facilitate team collaboration
10. Assign roles in the team (related to 7. but also more on the governance side of things - e.g. having a clear lead role to drive things forward is very beneficial to make sure progress is made) 
11. Find the best/right tools that work for your team for communication, meetings, issue management, project management and knowledge sharing

**Comment by tobyhodges** [comment]
Related to #138

**Comment by sstevens2** [comment]
7 and 10 could maybe also be combined somehow - Assign tasks and roles to distribute the responsibilities - This includes assigning larger roles to team members and assigning specific issues/tasks to collaborators.

**Comment by anenadic** [comment]
Here is another attempt at the top ten tips for collaboration - this time taking into account the order of things (as rightly pointed out by @sstevens2). I decided to go with the order of first documenting your project - then sorting out internal workings of the team - then moving on to working more and welcoming new collaborators. Other suggestions welcome - in terms of ordering and actual tips (some tips are more wordy/lengthy - should we look to even them out a bit more?). 

1. Provide ‘external-facing’ features for your lesson (such as description, objectives, contribution and 'how to get involved' guides, preferred way of communication) - these will be universally useful for your team too.
2. Find the best tools that work for your team for communication, documentation and knowledge sharing, issue & project management.
3. Document and share knowledge to facilitate team collaboration.
4. Plan your meetings to get the most out of your team (e.g. set agenda, assign meeting roles - chair, notetaker, time-keeper) and be appreciative of people's times.  
5. Share decisions and communicate with your team synchronously and asynchronously.
6. Record and manage issues with your lesson as you develop, trial and maintain it (e.g. assign people responsible for issues, categorise and prioritise them).
7. Assign tasks and roles to distribute the responsibilities - this includes assigning larger roles (project management & governance) to team members and assigning specific issues/tasks to collaborators. Progress is much more likely to be made when people know what they and others should be working on.
8. Be open and welcoming to new contributors and provide different opportunities to get involved with your project (from novice to expert collaborators). Point to upskilling guides (or run upskilling sessions if possible) to bring people up to speed. Show appreciation for everyone's contributions.
9. Manage contributions in a timely manner by noticing when things happen and responding to new issues, comments and Pull Requests (PRs).
10. People bring different perspectives, expertise and skills to a collaborative project and, while they can be productive and harmoniously complement each other, having some decision making and conflict resolution process in place will make sure progress can be made when disagreements arise.  

What thoughts do the others have @tobyhodges @sstevens2 @mkuzak ?

**Comment by tobyhodges** [comment]
I like this list, @anenadic. I have a few suggestions for further improvement, but would welcome a pull request to add this to the lesson: commenting and suggesting changes is a lot easier in a PR than an issue. 

I guess we also need to talk about where and how this should be inserted into the lesson. What can we cut down if this list is introduced? One suggestion follows: 

---

When discussing live coding in Instructor Training, trainees are given a brief introduction and presented with [an exercise](https://carpentries.github.io/instructor-training/17-live.html#compare-and-contrast) to watch videos that demonstrate live coding in action, and provide feedback on those examples. The "top ten tips" list is provided after that exercise has been completed.

Could we adopt a similar model here? For example, after a short introduction discussing why we promote a collaborative approach to lesson development and maintenance, we could present trainees with an exercise to explore some example lesson repositories (this one, plus two or three others) and note down what things they find that they think could aid collaboration. After discussing what people found, we could present the "top ten tips" list you have composed, and follow that up with additional detail where essential and exercises to implement the recommendations on their repositories.

(Note: this would be a pretty major re-write/re-organisation of the existing content, so if we decided to pursue this I would no longer aim to include the change in the Beta Release.)

**Comment by anenadic** [comment]
PR #273 created to address this.
