### ISSUE TITLE
Add a reflection exercise on "top ten recommendations" for collaborative lesson development in the wrap-up episode

### ISSUE THREAD

**Issue by anenadic** [carpentries/lesson-development-training#234]
See the discussion in:
https://github.com/carpentries/lesson-development-training/issues/233

**Comment by sstevens2** [comment]
Moving @anenadic's suggestions here so folks don't have to look them up in #233 

> Identify target audience for your lesson
Define desired learning outcomes for the lesson
Define an (ideally authentic) example dataset or narrative for the lesson
Design assessments to determine progress towards desired outcomes and to fit the example dataset/narrative chosen
Write content to lead learners from one of the assessments to the next following the story you are telling with your lesson
Assess learner progress towards outcomes during teaching
Pilot your lesson and evaluate how closely the outcomes meet the objectives.
Refine the lesson based on the feedback from pilots.
Keep to scope of your target audience and lesson objectives. It is OK to say 'No'.
Do not do it alone - collaborate with your team

**Comment by anenadic** [comment]
Closed via #273
