### ISSUE TITLE
In Carpentries Workbench episode, specifically point out Actions tab

### ISSUE THREAD

**Issue by MikeTrizna** [carpentries/lesson-development-training#241]
I've found that being able to show that the reason that the changes aren't immediately reflected is because the page is being built behind the scenes. Without diving too much into the weeds, seeing the gears moving and the status color change from yellow to green is satisfying too. GitHub Page builds just break from unknown reasons all the time (or known - YAML formatting issues), so it's good to be able to point to a specific error on why a change wasn't implemented.

**Comment by sstevens2** [comment]
@MikeTrizna and @tobyhodges Any suggestions on where/how to add this?  I was thinking about doing a call out on checking the status of the rendering website either before the `config.yaml` section or before the "Adding Lesson Content" Section in the [Workbench episode](https://carpentries.github.io/lesson-development-training/infrastructure.html)

**Comment by tobyhodges** [comment]
I would recommend adding it as a callout or Trainer Note at the start of "Adding Lesson Content", because trainees should have made a few commits by then and it might be clearer that actions are triggered by every commit (to main).

**Comment by sstevens2** [comment]
Thanks for the 2nd opinion!  Will assign and make the PR now.

**Comment by MikeTrizna** [comment]
I would actually recommend adding it before the "Configuring a Lesson Repository" section. That section contains the quote "It should already be generating a rendered version of the template repository. If it isn’t, the instructor should work with groups to turn on GitHub Pages." I think the GitHub Actions tab is the prime location for troubleshooting (even to see whether or not a render process kicked off or not?), so it's good to set the stage early.

**Comment by sstevens2** [comment]
That does seem like a good point.  If I put it there, I'm mostly worried that will be too many boxes together since there is already a callout about `main` vs `gh-pages` there and an instructor note telling how to turn on GitHub Pages.

**Comment by sstevens2** [comment]
Talked to @anenadic about this issue and we decided to update the branches call out to be about branches and gh-actions with a new paragraph about the gh-actions tab.  Then I'll update the troubleshooting the instructor note at the bottom to include that it would be a good chance to show the gh-actions tab too.
