### ISSUE TITLE
Add a table summarising lesson site setup steps

### ISSUE THREAD

**Issue by tobyhodges** [carpentries/lesson-development-training#248]
`episodes/infrastructure.md`: @AnnBackhaus suggested adding a table of the steps that will be taken in the episode, including a column of how often developers are likely to need to take these steps e.g. "only once" (creating the repo), "rarely" (adjusting `config.yaml`, creating an episode), "often" (editing episode Markdown).

**Comment by tobyhodges** [comment]
Here is the table as I would summarise it.

| Setup step | Frequency |
|------------|-----------|
| Create repository | Once |
| Add collaborators | Rarely |
| Edit global lesson configuration file | Rarely |
| Edit lesson front page | Rarely |
| Create a new episode | Often in early stages of lesson design, rarely after that |
| Edit episode content | Often |

**Comment by anenadic** [comment]
Looks good to me 👍 @tobyhodges.
