### ISSUE TITLE
Explain lesson stages

### ISSUE THREAD

**Issue by anenadic** [carpentries/lesson-development-training#25]
Describe different stages a lesson goes through during development - pre-alpha, alpha, beta, stable. I think Toby's already added this somewhere in the Incubator and it may already be somewhere in the lesson. If it is not - it could perhaps go somewhere towards the end of the lesson, in the "collaborating" episodes?

**Comment by mkuzak** [comment]
This is covered in [Lesson life cycle chapter in Curriculum development handbook](https://carpentries.github.io/curriculum-development/the-lesson-life-cycle.html). I suppose we should not be replicating it. Maybe we should add an exercise that composes of reading of this chapter and having a discussion around it.

**Comment by anenadic** [comment]
Exercise sounds good - people need to have a clear understanding of different stages of lesson development, especially since we may be mentioning these stages later in the material when we talk about trialling lessons.

**Comment by tobyhodges** [comment]
I hope this is now covered in `17-operations`. I will close for now and we can reopen if we feel this needs more work after the pilot next week.
