### ISSUE TITLE
Describe how we intend callouts to be used?

### ISSUE THREAD

**Issue by tobyhodges** [carpentries/lesson-development-training#257]
While prepping #256, I was reflecting on how we are using callouts for optional material that could be covered at the Trainers' discretion/to pre-empt questions from trainees. Furthermore, the number of callouts in the curriculum is getting quite large (16 at time of writing) so could translate to a large difference in total teaching time if all were covered in full. 

However, there is real variation in how callouts are used across lessons: some lessons seem to use them to highlight something particularly important, to encourage Instructors to emphasise this content. Which is pretty much the exact opposite of how we are using them! 😆 

If we are going to keep using callouts this way, I think it would be sensible to add something to the Instructor Notes page to explain our intention.

The alternative, [when the spoiler class of fenced div is introduced in the next release of `sandpaper`](https://github.com/carpentries/sandpaper/pull/502#issuecomment-1698203526), would be to replace these callouts with expandable/collapsible spoilers. That would save some space on the page and would have the advantage of visually implying the optional nature of the content they contain.

What do you think @sstevens2 @mkuzak @anenadic?

**Comment by sstevens2** [comment]
I agree it would be good to be consistent about how we use callouts.  I'm somehow a little hesitant to put the optional material in the spoiler callouts but can't quite articulate why.  I'd be willing to give it a try though and see how it goes.

**Comment by sstevens2** [comment]
I rescind my previous comment.  I think we should recommend callouts for highlighting and spoilers for optional materials - with Toby's info about making sure the titles are useful - answers to questions so trainers can decide if they think the learners need the answer to that question.

**Comment by sstevens2** [comment]
Also need to change our curriculum to match this recommendation as part of the PR for this issue
