### ISSUE TITLE
Change the list of issue labels in team collaborating episode

### ISSUE THREAD

**Issue by sstevens2** [carpentries/lesson-development-training#260]
Moving from PR #258 into own issue. Suggestion that we link to a [resource on GitHub default labels](https://docs.carpentries.org/topic_folders/maintainers/github_labels.html) and instead talk about the Carpentries labels and how to get them into your repo in the team collaborating episode.

**Comment by tobyhodges** [comment]
Relevant page in the community handbook: https://docs.carpentries.org/topic_folders/maintainers/github_labels.html
