### ISSUE TITLE
Preparing to teach

### ISSUE THREAD

**Issue by smcclatchy** [carpentries/lesson-development-training#28]
People tend to focus more on the teaching than they do on everything that leads up to the teaching event. Often the teaching isn't what makes a training successful - it's all of the organization that leads up to the teaching that determines success. Commonly overlooked are these critical organizational steps that can make or break a training:

1. getting the right people in the room
2. communicating what they need to do to prepare for the training 

This means: 

- selecting dates that don't conflict with holidays or big events like conferences or symposia, and that don't overlap with other training events 
- advertising the training well in advance (optimally 1 month or more) in many channels to make sure people see it at least once (i.e. mass e-mail, Slack, institutional website, newsletter); re-advertising to remind people (2 weeks before) 
- including learning outcomes and prior knowledge when advertising the training - these tell people whether or not they are a good fit for the training
- including registration questions modeled after the [pre-assessment questionnaire](https://teachtogether.tech/en/index.html#s:checklists-preassess) to check that registrants are a good fit for the training; if not, follow up with them to make sure that they know that the training is above or below their skill level
- sending out software installation and data download instructions one week or so before the training, with a reminder a few days before

**Comment by tobyhodges** [comment]
Thanks @smcclatchy. I wonder if a couple of your points,

>- selecting dates that don't conflict with holidays or big events like conferences or symposia, and that don't overlap with other training events
> - advertising the training well in advance (optimally 1 month or more) in many channels to make sure people see it at least once (i.e. mass e-mail, Slack, institutional website, newsletter); re-advertising to remind people (2 weeks before)

will be better placed elsewhere? E.g. in the Instructor Training curriculum or the information and checklists for workshop hosts in the Community Handbook.

But the other three,

> - including learning outcomes and prior knowledge when advertising the training - these tell people whether or not they are a good fit for the training
> - including registration questions modeled after the [pre-assessment questionnaire](https://teachtogether.tech/en/index.html#s:checklists-preassess) to check that registrants are a good fit for the training; if not, follow up with them to make sure that they know that the training is above or below their skill level
> - sending out software installation and data download instructions one week or so before the training, with a reminder a few days before

are definitely good to include in this curriculum. I would say these fit in the _Preparing to teach_ section, and in the relevant part of the training where prerequisites/outcomes, target audience, and setup instructions are each first discussed.

**Comment by smcclatchy** [comment]
I think yes - the first points are administrative, the others pedagogical. Even the point about software installation and data download might go elsewhere since this is administrative in nature as well.

**Comment by tobyhodges** [comment]
Administrative, yes. But it doesn't harm to mention it when we are teaching about writing setup instructions here.

**Comment by yabellini** [comment]
Not being able to install what you need correctly is one of the most significant sources of frustration. Definitely worth mentioning.

Maybe suggest that:
- Sending the instructions in advance 
- Doing some initial exercise to check that everything is well installed, 
- have an alternative plan for those who can't have their setup running on their machine (at least for the first class) like RStudio Cloud or similar for other languages 

I always have that alternative for those who can't have their setup running.

**Comment by anenadic** [comment]
I agree that preparing to teach is a combination of administrative and pedagogical tasks but that the organisational side of things are really critical to having a successful pilot. 

I'd add preparing and designing a feedback form as one of the things - it's such a tricky task at this stage as you are evaluating not just whether your training is a having a desired effect on learners but the material design and choice of topics and exercises and whether it fits the target audience as well. @tobyhodges mentioned some of these things would be included in an Extra page "For Learners" as guidance for trial runs (see #7) - I suggest we highlight some of these things in "Preparing to teach" episode and emphasise the link to the Extra page with guidance from here.

**Comment by sstevens2** [comment]
I agree with adding in the pieces that are needed to help with organizing pilots.

This discussion has me thinking we need a separate "how to host/organize a workshop" lesson/workshop someday.  This lesson helps offload some of the burden of lesson development from instructor training.  Might be useful to breakout the host role a bit more from instructor training and lesson development training.  We always separate out this role from instructing at my Uni to take some of the pressure off instructors.
