### ISSUE TITLE
Links to Markdown and RMarkdown templates should point to respective repos

### ISSUE THREAD

**Issue by anenadic** [carpentries/lesson-development-training#309]
In episode https://carpentries.github.io/lesson-development-training/infrastructure.html - I think it would be better that the links to Markdown and RMarkdown templates (see picture below) point to the actual repos and not the "copy from this template action":

<img width="785" alt="image" src="https://github.com/carpentries/lesson-development-training/assets/631719/d7bc4455-7107-41f6-a9f5-ccdc069ff6d9">

We could say that learners should click the "Use this template" button on the repo as that teaches them how to use template repositories in general. It also gives them a chance to explore the repo a bit (should they wish to) whereas the embedded link to generate template we currently use does not convey this kind of information and I think learners lose out a bit there (it is also hard for learners to figure our the real repo URLs from the "generate from template URLs").  Happy to do a PR if others think this is a good idea.

**Comment by thisHermit** [comment]
I created a PR to resolve this issue as part of my checkout process. Please let me know if this matches your expectations @anenadic .
