### ISSUE TITLE
Reuse the iterative & backward lesson design image

### ISSUE THREAD

**Issue by anenadic** [carpentries/lesson-development-training#310]
Reuse the iterative & backward lesson design image (created by @sstevens2's team member)
<img width="1147" alt="image" src="https://github.com/carpentries/lesson-development-training/assets/631719/1fa68eae-ad0d-44b1-aa72-9085c83a9935">
from Sarah and Aleks's ADSA conference/workshop slides: https://docs.google.com/presentation/d/1EQW1qCNrVN61ZA1SR_orXcBgGYvB7OC1u3Ju1FFXujo/edit#slide=id.g28bbae282b8_0_858 to replace the current ones in https://carpentries.github.io/lesson-development-training/lesson-design.html. 

We'd need an SVG for this to be more useful to us.

**Comment by sstevens2** [comment]
@navin2uw would you be okay with use re-using this image?  Do you by any chance have an svg version?

**Comment by navin2uw** [comment]
yes that is fine and I think this file might work.
![Carpentries Diagram](https://github.com/carpentries/lesson-development-training/assets/137317535/b2b9d30b-766a-4429-9efd-d1082724f155)
