### ISSUE TITLE
A reflection exercise to move/skip

### ISSUE THREAD

**Issue by anenadic** [carpentries/lesson-development-training#317]
Reflection exercise in https://carpentries.github.io/lesson-development-training/explanation.html (shown below) while very nice perhaps can be skipped or moved to the wrap up that comes after that episode as there often is no time.

#### Reflection Exercise (20 minutes)
We have reached the end of the time you have to work on the episodes of your lesson in this training. This exercise provides you with a chance to look back over everything you have sketched out for your episode and the lesson as a whole and consider what still needs to be done before it can be taught.
You can use this time however you judge will be most beneficial to your preparations for teaching your episode in a trial run.
If you are not sure how to start, consider mapping out the relationships between the objectives of your episode and the examples and exercises via which they will be taught and assessed.

**Comment by tobyhodges** [comment]
I like the idea of combining it with the _Organise your Knowledge_ exercise in the wrap-up that comes shortly after.
