### ISSUE TITLE
Revisit mini wrap up episodes and when they happen in the curriculum

### ISSUE THREAD

**Issue by anenadic** [carpentries/lesson-development-training#322]
The mini wrap-up episodes often do not coincide with the actual schedule - perhaps we could see how to fold them into the existing episodes or remove them altogether?

**Comment by tobyhodges** [comment]
Let's discuss this at Maintainers meeting today.

**Comment by sstevens2** [comment]
Was there a resolution from maintainers meeting?

**Comment by tobyhodges** [comment]
Thanks for the prompt, @sstevens2! Those Trainers present (@anenadic, @miketrizna and me) agreed on the following resolution:

> remove first wrap-up episode, make reflection exercise [from that wrap-up] an optional homework task at end of _Defining Episode Objectives_ 

If you have no concerns about that, I will go ahead and remove it.
