### ISSUE TITLE
Rename exercise "Assessing an objective"

### ISSUE THREAD

**Issue by anenadic** [carpentries/lesson-development-training#329]
Exercise: Assessing an Objective in "Designing Assessments" episode could be renamed as "design an exercise to assess a learning objective" - the confusion arises from the word "assess" being taken to mean "critique".

**Comment by tobyhodges** [comment]
How about _"Assessing Progress Towards an Objective"_?

**Comment by anenadic** [comment]
Or "Checking progress towards and objective"? I am OK with either.
