### ISSUE TITLE
Text of including images mentioned twice

### ISSUE THREAD

**Issue by anenadic** [carpentries/lesson-development-training#340]
Maybe remove the one in https://carpentries.github.io/lesson-development-training/narrative.html#finding-images and keep the discussion in https://carpentries.github.io/lesson-development-training/explanation.html

**Comment by tobyhodges** [comment]
The two sections cover different aspects of images: https://carpentries.github.io/lesson-development-training/narrative.html#finding-images focuses on licensing and re-use, while https://carpentries.github.io/lesson-development-training/explanation.html talks about image accessibility. To me, these feel like they are in their appropriate locations. Could you expand more on what you would cut/how it might help to combine the content into a single section please @anenadic?

**Comment by anenadic** [comment]
It does make sense that we cover these two different aspects (an those locations they are now at) - I am not sure what text I thought was duplicated or whether things have changed since I made this issue? Who knows - it all looks good to me atm. Happy for this to be closed.
