### ISSUE TITLE
Rendering of code blocks in section titles in infrastructure lesson

### ISSUE THREAD

**Issue by anenadic** [carpentries/lesson-development-training#346]
In episode https://carpentries.github.io/lesson-development-training/infrastructure.html
code blocks for `config.yml` and `README` in section titles get rendered without blank space before them:

<img width="562" alt="image" src="https://github.com/carpentries/lesson-development-training/assets/631719/45b45b08-a025-4a12-aaa4-822d0f2e54bd">

<img width="759" alt="image" src="https://github.com/carpentries/lesson-development-training/assets/631719/752e9281-9142-40c3-99fa-64dcd09c0a56">

This it likely due to the way code block in translated into HTML, where the blank space in the text just preceding code block is being wiped off:

<img width="251" alt="image" src="https://github.com/carpentries/lesson-development-training/assets/631719/12d6511d-76c5-42fc-88df-1163512b5265">

The same goes for the text after the code block.
The easy, if not elegant solution, would be to include an extra blank at the beginning and end of the code text, e.g. \` config.yml \` and \` README.md \` as then the blank spaced would end up inside the \<code> \</code> tags.

**Comment by tobyhodges** [comment]
I'm going to close this here, as it is being tracked in the sandpaper repo
