### ISSUE TITLE
Trainee feedback: Lesson Design & Target Audience sections

### ISSUE THREAD

**Issue by tobyhodges** [carpentries/lesson-development-training#364]
### How could the content be improved?

An excerpt from a minute card feedback response:

> Some of the background knowledge felt a little disconnected from the content of the lesson. Maybe reflow how much of the Nicholls phases can be recast as organizational structure for the schedule of the lesson, and redirect some of the content into examples (e.g. expertise levels -> ideating the target audience)

I interpret this as two suggestions for improvement:

1. After introducing the iterative design process, provide an overview of the curriculum for this training and highlight how the training is organised to follow one cycle through that process.
2. (Moved to #435) ~~Provide more examples of exactly what we will be doing at each stage of the process, and more examples generally e.g. by discussing how considerations of expertise level might be captured in your description of target audience.~~

**Comment by anenadic** [comment]
I was not sure how to interpret that comment myself - but your interpretation seems pretty good to me @tobyhodges.

**Comment by anenadic** [comment]
I think this may also be a good point to stress/reiterate that they will not be having a finished product/finished lesson and that they should continue to work on what was covered on the day in between teaching sessions. This came out from the training @tobyhodges and I did 10-13 September 2024.

**Comment by anenadic** [comment]
@tobyhodges feels like it is a good idea to talk about theory a bit at the start (similar to instructor training) to understand why we recommend the things we do to them

**Comment by sstevens2** [comment]
Decided to move #2 suggestion to new issue as it is a longer effort and not required for the milestone
