### ISSUE TITLE
Context on Lesson and Episode Learning Objectives

### ISSUE THREAD

**Issue by sstevens2** [carpentries/lesson-development-training#368]
### How could the content be improved?

The examples in the Lesson Learning Objectives are episode level learning objectives.  Think we need to add some context about Lesson -> episode learning objectives in this episode.  Also @ErinBecker has a suggestion for rearrangement that might help.

### Which part of the content does your suggestion apply to?

https://carpentries.github.io/lesson-development-training/objectives.html

**Comment by ErinBecker** [comment]
Thanks @sstevens2! I put my comment about re-ordering the content to group lesson level and episode level LOs together (and move workbench to after those two topics are completed) in https://github.com/carpentries/lesson-development-training/issues/97#issuecomment-2122950225.

**Comment by sstevens2** [comment]
Moving here for convenience 

 > In teaching last week, it seemed to me that having the learners develop lesson level LOs, then learn about the workbench, then come back to write episode level LOs was a bit disjointed. I think it would be better to have learners work through both types of LOs before starting learning the workbench.
> 
> _Originally posted by @ErinBecker in https://github.com/carpentries/lesson-development-training/issues/97#issuecomment-2122950225_

**Comment by sstevens2** [comment]
Working on in branch [iss369](https://github.com/carpentries/lesson-development-training/tree/iss368)

**Comment by anenadic** [comment]
I think this is now addressed by proxy via #385 - unless we can be more clear about the distinction between lesson and episode objectives, I suggest we close this issue. Any thoughts @sstevens2 @tobyhodges ?

**Comment by anenadic** [comment]
Closing as fixed elsewhere but more examples of lesson level and episode level objectives would be good.
