### ISSUE TITLE
Integrate Lesson Design Notes Template

### ISSUE THREAD

**Issue by sstevens2** [carpentries/lesson-development-training#371]
### How could the content be improved?

In maintainers meeting we discussed more closely aligning the lesson design notes template with the curriculum.  This includes updating the curriculum to reference it whenever it is needed by the leaners and restructuring the lesson design notes template to match the order of CLDT better.

**Comment by sstevens2** [comment]
This was also suggested in our first workshop where we added in the use of the lesson design notes template.

**Comment by tobyhodges** [comment]
This was partially addressed by #395, which updated the curriculum to mention the notes document in the relevant exercises. I have taken a pass at updating [the design notes template]() to match this new training structure. I will report back on our experience after @anenadic and I try teaching the thing this week.
