### ISSUE TITLE
Broken link in Defining Lesson Objectives/Outcomes episode

### ISSUE THREAD

**Issue by josenino95** [carpentries/lesson-development-training#379]
### What is the problem?

One of the exercise boxes has a link to a tool developed by the University of Manchester, which by the description seems to evaluate learning objectives. But the [link to the tool](https://web.cs.manchester.ac.uk/iloadvisor/) is not currently working.

### Location of problem (optional)

https://carpentries.github.io/lesson-development-training/objectives.html#exercise-reviewing-lesson-objectives-15-minutes

**Comment by tobyhodges** [comment]
Thanks for reporting @josenino95. @anenadic please could you check with folks at UoM to see if the resource can be brought back online?

**Comment by anenadic** [comment]
Submitted a ticket (#938987) with IT services

<img width="740" alt="image" src="https://github.com/user-attachments/assets/f4e39d06-6182-4ccd-82be-625271cf9ed4">

**Comment by anenadic** [comment]
This has now been fixed by the Chris Page from the Mcr CS IT support, see the email below:

```
On 05/08/2024 09:08, Christopher Page wrote:
Hi,

This has been fixed now. Initial tests I've done seem to indicate that it is working normally, I would be grateful if you could confirm.

Chris

-- 
Technical Operations Manager (Computing)
LF28, Kilburn Building,
The University of Manchester
Tel: 0161 275 6268

> Just as an update - looking at this at the moment, looks like a recent update switched the python version for flask. I'm fixing, and will get back to you once it's sorted.
>
> Chris
>

```
