### ISSUE TITLE
Move lesson design theory into first part of the training and Workbench and lesson operation into second

### ISSUE THREAD

**Issue by anenadic** [carpentries/lesson-development-training#385]
### How could the content be improved?

This is a proposal to replace issue #178 and address #97 at the same time. Part of this issue is also addressed in PR #380.

Based on #178 and #97, discussions with learners and between trainers, in order to reduce the cognitive load on learners and switching between design and implementation, this issue will reorganise episodes so that lesson design is taught on the first full day, and then Workbench, how we operate, and preparing to teach on the second full day.

We already have the [lesson development template](https://codimd.carpentries.org/HPwUE3FnTeSQJ9-_5EfU7Q?view#) which learners are using to put their lesson design notes so they can carry on using it until we switch to the Workbench part where they copy/paste their content in the lesson repository.

I propose the following new structure:

1. Lesson Design
2. Identifying Your Target Audience
3. Example Data and Narrative (I am minded to move this episode here although it could go after defining lesson objectives too - if I remember correctly there was some feedback about the narrative/dataset selection being covered too far into the lesson design and they should be thinking about it earlier)
4. Defining Lesson Objectives/Outcomes
5. Episodes and Defining Episode Objectives
6. Designing Exercises
7. How to Write a Lesson (move this before The Workbench episode as this it still "theoretical" episode)
8. The Carpentries Workbench
9. Adding Lesson Content (new episode, breaking the Workbench episode at the current "Adding Lesson Content" section and including the content of the current Implementing Exercises episode and then the "filler text" in-between exercises)
10. How we Operate
11. ... and so on

This needs discussing with the trainers group.

Fixes #178.

**Comment by anenadic** [comment]
This is a massive reorganisation and needs a wider discussion. We could also think about doing this in a number of smaller PRs so as to avoid mammoth changes - e.g. first sort out the first part of the lesson that covers 1 full day of teaching and then move to the second part - any other suggestions welcome.

**Comment by tobyhodges** [comment]
Generally speaking, I really think this is worth trying and the plan laid out above is good. Summarising some in-person discussion at RSECon, about tweaks to the list above:

1. Example Data & Narrative would need to come after Lesson Objectives -- we cannot expect trainees to know what to look for in a dataset/narrative if they have not defined what they most want to teach people.
2. Before moving anything around, I would like to compile a full list of all of the exercises that will need to be moved later in the curriculum and/or adjusted to account for the reorganisation
