### ISSUE TITLE
Remove the Break episodes?

### ISSUE THREAD

**Issue by tobyhodges** [carpentries/lesson-development-training#396]
### How could the content be improved?

I wonder if we would be better off removing the break episodes? It has proven awkward during training events to insert breaks exactly where they appear in the curriculum, and I think we might be better off taking them out and instead trying to curate a recommended schedule in `instructor-notes.md`?

**Comment by sstevens2** [comment]
I think I'd prefer that. I find it a bit annoying to skip them when I'm teaching and I never take the breaks exactly at those times.
