### ISSUE TITLE
Move fenced divs to a separate subsection in adding lesson content episode

### ISSUE THREAD

**Issue by anenadic** [carpentries/lesson-development-training#415]
### How could the content be improved?

Fenced divs should be covered in a separate subsection in https://carpentries.github.io/lesson-development-training/lesson-content.html. They could either be introduced after lesson's home page before we go into adding them in episodes, or after adding episodes section. The more I think about this, the more I am inclined to cover them before adding episodes - e.g. have a section that talks about structural components of page content.

### Which part of the content does your suggestion apply to?

https://carpentries.github.io/lesson-development-training/lesson-content.html

**Comment by tobyhodges** [comment]
Thanks @anenadic, let's discuss this at our next Maintainers' meeting

**Comment by anenadic** [comment]
The consensus seems to be to use the first fenced div for prerequisites and then mention other types, and then move onto adding episodes and using more fenced divs.

Also consider turning the demo of adding episode content into an exercise.
