### ISSUE TITLE
Update Structure of CLDT image

### ISSUE THREAD

**Issue by sstevens2** [carpentries/lesson-development-training#425]
### How could the content be improved?

When we feel the curriculum has settled in rearrangements, we should update the Structure of CLDT image in the intro episode.  I realized when teaching it yesterday that we don't start to teach infrastructure until the 3rd half day and then we integrate them after that.

### Which part of the content does your suggestion apply to?

https://carpentries.github.io/lesson-development-training/introduction.html

**Comment by tobyhodges** [comment]
Based on discussion at today's Maintainers meeting, I think we should take care of this before we mark the lesson as stable and make the next release
