### ISSUE TITLE
Encourage trainees to use varied examples to teach abstract concepts

### ISSUE THREAD

**Issue by tobyhodges** [carpentries/lesson-development-training#46]
From [this lightning talk by Neil Brown](https://neverworkintheory.org/2022/05/25/brown-mind-learns.html) in the _Never Work in Theory_ series:

> Use varied examples if you want to teach abstract concepts.

**Comment by sstevens2** [comment]
I've been converging on this idea when I advise a group working on a lesson about data exploration.
