### ISSUE TITLE
Small reorganisation of episodes 'Your lesson' and 'Target Audience'

### ISSUE THREAD

**Issue by anenadic** [carpentries/lesson-development-training#64]
I suggest renaming the episode 'Your lesson' to 'Lesson design' and moving the first section of 'Target Audience' episode titled 'A Lesson Design Process' to top of the 'Your lesson' episode, and then follow it with the existing text from that episode under a new section titled "Your lesson(s)".

The main reason is that (if we go ahead with the changes) we will have the first (actual teaching) episode titled "Lesson design" which is the (main) topic of the course so it fits nicely. We then explain the 5 steps of the lesson design in that episode and carry on addressing each of these steps in a separate suitably titled episode. The episode 'target audience' currently starts with the text on lesson design, which is not a big problem but I think deserves an episode on its own - plus then the target audience episode can start by addressing what says in the title.

**Comment by tobyhodges** [comment]
I like this proposal.
