### ISSUE TITLE
Discuss appropriate use of images in online lessons

### ISSUE THREAD

**Issue by tobyhodges** [carpentries/lesson-development-training#90]
During the first pilot, during _How to write a lesson_ or perhaps _Example Data and Narrative_, a participant asked about good practices in (re)using images in a lesson. @jbkieffer contributed a very good answer about image attribution, licensing, and copyright, that I would love to see contributed into this curriculum.

@jbkieffer: would you be willing to open a pull request to add some guidance to this curriculum about using images in lessons?

**Comment by tobyhodges** [comment]
There is no hurry, and I would be very grateful to you for doing it when you have time. Our next pilot will not take place for at least another three months.

If you prefer to put the info here and allow us to incorporate it, that is also ok, but I would much prefer to merge a PR 😄

**Comment by jbkieffer** [comment]
Got it - I will add this to my list, and it's good practice for PRs, too!

**Comment by tobyhodges** [comment]
Closed by @jbkieffer in #143
