### ISSUE TITLE
add instructor notes about concepts covered more than once

### ISSUE THREAD

**Issue by tobyhodges** [carpentries/lesson-development-training#93]
To help guide Trainers on when they can keep their discussion brief on a particular topic, we could add instructor notes next to sections of the curriculum where a concept is introduced that will be covered in more detail later. Perhaps also notes next to the follow-up content that appears later, to remind the trainer that a concept has already been introduced/has been covered in detail already (as appropriate).

**Comment by anenadic** [comment]
Closing as covered eleswhere.
